### ISSUE TITLE
The Slack Invite Link has expired

### ISSUE THREAD

**Issue by linderr** [bccovid-19/printfiles#23]
Hi! My name is Linda and I am from www.findthemasks.ca
I spoke on the phone with Petko to join the Slack group but your link has already expired on both your main website as well as the README file on GitHub.

Please share or update a Slack link - thank you!

**Comment by dan-bcc3d** [comment]
Hi linderr,

This has been fixed in https://github.com/bccovid-19/track/commit/aeb433f5ef4bd49216f60c0f2c8a6f111b863b31

Regards,
Dan
